version: "3.9"

###############################################################################
# FlashProxy – Auth Stack
###############################################################################

services:
  # ────────── Redis (credentials DB) ──────────
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    network_mode: host             # binds :6379 on the VM
    command:                       # list form → no accidental comment tokens
      - redis-server
      - --appendonly
      - "yes"                      # enable durable AOF
      - --requirepass
      - "${REDIS_PASS}"            # password from .env / secret
    volumes:
      - redis_data:/data
    env_file:
      - .env

    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $REDIS_PASS ping | grep PONG || exit 1"]
      interval: 10s
      retries: 5
      timeout: 3s

  # ────────── SPOE auth-agent ──────────
  auth-spoa:
    build:
      context: .                   # current dir has Dockerfile + main.go
      dockerfile: Dockerfile
    container_name: auth-spoa
    restart: unless-stopped
    network_mode: host             # binds :9000 on the VM
    depends_on:
      - redis
    env_file:
      - .env
    command:
      - -listen=:9000
      - -redis=127.0.0.1:6379
      - -redis-password=${REDIS_PASS}

volumes:
  redis_data:
