version: "3.9"

services:
  redis:
    image: redis:7.2-alpine
    network_mode: host
    command:
      - sh
      - -c
      - |
        exec redis-server --appendonly yes --requirepass "$REDIS_PASS"
    volumes: ["redis_data:/data"]
    env_file: [.env]            # runtime env for redis-server

  auth-proxy:
    build: .
    network_mode: host
    depends_on: [redis]
    env_file: [.env]            # gives REDIS_PASS to the proxy
    command:
      - -listen=:443
      - -backend=127.0.0.1:8443
      - -redis=127.0.0.1:6379
      - -max-gbps=1

volumes:
  redis_data:
