#cloud-config
package_update: true
packages: [docker.io, curl, tar]

write_files:
  ########################################################
  # Promtail config — scraped by docker‑compose service
  ########################################################
  - path: /opt/src/promtail.yaml
    permissions: '0644'
    content: |
      server:
        http_listen_port: 0
      positions:
        filename: /var/log/positions.yaml
      clients:
        - url: http://localhost:3100/loki/api/v1/push
      scrape_configs:
        - job_name: flash-edge
          static_configs:
            - targets: ['localhost']
              labels:
                job: flash-edge
                __path__: /var/log/*proxy*.log

runcmd:
  - systemctl enable --now docker

  # ─── Fetch and extract fp‑prod release v0.11 ──────────────────────
  - mkdir -p /opt/src
  - curl -L https://github.com/thealonlevi/fp-prod/archive/refs/tags/0.11.tar.gz -o /opt/src/fp-prod-0.11.tar.gz
  - tar -xzf /opt/src/fp-prod-0.11.tar.gz --strip-components=1 -C /opt/src

  # ─── Start the edge stack (HAProxy, 3proxy, Loki, Grafana, Promtail) ───
  - docker compose -f /opt/src/flashproxy-infra/flash-gateway-mvp/docker-compose.yml up -d

final_message: "🚀 FlashProxy edge ready: HAProxy & observability stack running."
