auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

analytics:
  reporting_enabled: false           # opt-out of usage stats

###############################################################################
# Single-node ring (in-memory) + unified data directory
###############################################################################
common:
  path_prefix: /loki                 # root for all data dirs
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1

###############################################################################
# Storage
###############################################################################
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location:         /loki/index_cache
    cache_ttl:              24h
    shared_store:           filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store:      filesystem

ingester:
  wal:
    enabled: true
    dir: /loki/wal

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
