auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  root_path: /loki          # <- replaces deprecated "path"
  storage:
    filesystem:             # filesystem chunks & index
      chunks_directory: /loki/chunks
      rules_directory:  /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
