auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

storage_config:
  filesystem:
    directory: /loki          # single-node, local FS

schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
